In [ ]:
#importing libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from numpy import *

In [ ]:
#Numpy arrays
a=np.array([1,2,3,4])#1d array
b=np.array([[1,5,7,8],[3,5,6,9]])#2d array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])#3d array
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]])#4d array


In [ ]:
print(a)
print("\n")
print(b)
print("\n")
print(c)
print("\n")
print(d)


[1 2 3 4]


[[1 5 7 8]
 [3 5 6 9]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [ ]:
print("the shape of as is:",a.shape)

the shape of as is: (4,)


In [ ]:
sales_df=np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [300,400,650,89],
    [500,85,90,100]
])
sales_df[:,1]

array([  2,   6,  10, 400,  85])

In [ ]:
sales_df[(sales_df>100) & (sales_df>80)]

array([300, 400, 650, 500])

In [ ]:
sales_df[(sales_df>100) | (sales_df>80)]

array([300, 400, 650,  89, 500,  85,  90, 100])

In [ ]:
sales_df[:,1]

array([[5, 6, 7, 8]])

In [ ]:
sales_df[[3,3],3]

array([89, 89])

In [ ]:
#Broadcasting
a=np.array([1,2,3])
b=2
c=np.array([1,2,5])
print(a*b)
print(a+b)
print(a/c)



[2 4 6]
[3 4 5]
[1.  1.  0.6]


In [ ]:
#example sales_data 10% discount
day1_sales=sales_df[0]
discounted_sales=day1_sales*0.9
print(discounted_sales)


[0.9 1.8 2.7 3.6]


In [ ]:
fgg=ones([6,5],int)
print(fgg)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [ ]:
#Mathematical operations
example=array([12,56,7,8,9,10])
print(max(example))
print(min(example))
print(sum(example))
print(mean(example))
print(median(example))
print(std(example))
print(var(example))
print(sin(example))
print(cos(example))
print(tan(example))
print(log(example))
print(log10(example))
print(exp(example))
print(sqrt(example))

56
7
102
17.0
9.5
17.511900715418264
306.6666666666667
[-0.53657292 -0.521551    0.6569866   0.98935825  0.41211849 -0.54402111]
[ 0.84385396  0.85322011  0.75390225 -0.14550003 -0.91113026 -0.83907153]
[-0.63585993 -0.61127369  0.87144798 -6.79971146 -0.45231566  0.64836083]
[2.48490665 4.02535169 1.94591015 2.07944154 2.19722458 2.30258509]
[1.07918125 1.74818803 0.84509804 0.90308999 0.95424251 1.        ]
[1.62754791e+05 2.09165950e+24 1.09663316e+03 2.98095799e+03
 8.10308393e+03 2.20264658e+04]
[3.46410162 7.48331477 2.64575131 2.82842712 3.         3.16227766]


In [ ]:
#arrange()
arrange=np.arange(50,0,-3)
print(arrange)

[50 47 44 41 38 35 32 29 26 23 20 17 14 11  8  5  2]


In [ ]:
#logspace
logspace=np.logspace(1,10,5)
print(logspace)

[1.00000000e+01 1.77827941e+03 3.16227766e+05 5.62341325e+07
 1.00000000e+10]


In [ ]:
#linespace
linalge=np.linspace(1,10,5)
print(linalge)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
#reshape
reshape=np.arange(1,10).reshape(3,3)
print(reshape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
#practice
array1=np.arange(-2,10,1).reshape(2,6)
print("The element is:",array1)
print("the average is :",average(array1))
print("the sum is:",sum(array1))
print("the count of arrays is :",array1.size)
print(array1[array1<0])

The element is: [[-2 -1  0  1  2  3]
 [ 4  5  6  7  8  9]]
the average is : 3.5
the sum is: 42
the count of arrays is : 12
[-2 -1]


In [ ]:
#Empty
df1=df.fillna(0)
df1

In [ ]:
import pandas as pd
import numpy as np
data={
    "Name":["Alice","Bob","Charlie"],
    "Age":[25,30,35],
    "City":["New York",np.nan,"Los Angeles"],
    "Salary":[10000,200000,np.nan],
    "Department":["HR",np.nan,"IT"]
}

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df.isnull().sum()


Name          0
Age           0
City          1
Salary        1
Department    1
dtype: int64

In [ ]:
df=df.fillna({'City':'City Missing','Salary':0.0,})


In [ ]:
df

Name  Age         City    Salary Department
0    Alice   25     New York   10000.0         HR
1      Bob   30          NaN  200000.0        NaN
2  Charlie   35  Los Angeles       NaN         IT

In [ ]:
df.dropna(axis=1)

Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df.fillna({"Salary" : df["Salary"].mean()},inplace=True)
df

Name  Age         City    Salary Department
0    Alice   25     New York   10000.0         HR
1      Bob   30     New York  200000.0         HR
2  Charlie   35  Los Angeles  200000.0         IT

In [ ]:
sales={
    "Date" :["2024-01-01","2024-01-02","2024-01-03","2024-01-04"],
    "Region":["East","West",np.nan,"south"],
    "Units_Sold":[10,np.nan,15,12],
    "Units_Price":[300,250,400,np.nan]
}

In [ ]:
dff=pd.DataFrame(sales)
dff

Date Region  Units_Sold  Units_Price
0  2024-01-01   East        10.0        300.0
1  2024-01-02   West         NaN        250.0
2  2024-01-03    NaN        15.0        400.0
3  2024-01-04  south        12.0          NaN

In [ ]:
dff.isnull().sum()

Date           0
Region         1
Units_Sold     1
Units_Price    1
dtype: int64

In [ ]:
dff.fillna({"Region":"Region Missing","Units_Price":dff["Units_Price"].mean()},inplace=True)
dff

Date          Region  Units_Sold  Units_Price
0  2024-01-01            East        10.0   300.000000
1  2024-01-02            West         NaN   250.000000
2  2024-01-03  Region Missing        15.0   400.000000
3  2024-01-04           south        12.0   316.666667

In [ ]:
dff


Date          Region  Units_Sold  Units_Price
0  2024-01-01            East        10.0   300.000000
1  2024-01-02            West         NaN   250.000000
2  2024-01-03  Region Missing        15.0   400.000000
3  2024-01-04           south        12.0   316.666667

In [ ]:
dff.groupby("Region")["Units_Sold"].mean()

Region
East              10.0
Region Missing    15.0
West               NaN
south             12.0
Name: Units_Sold, dtype: float64

In [ ]:
dff.groupby("Region").agg({"Units_Sold":"sum","Units_Price":"mean"})

Units_Sold  Units_Price
Region                                 
East                  10.0   300.000000
Region Missing        15.0   400.000000
West                   0.0   250.000000
south                 12.0   316.666667

In [ ]:
dff[(dff["Units_Sold"]>10)]

Date          Region  Units_Sold  Units_Price
2  2024-01-03  Region Missing        15.0   400.000000
3  2024-01-04           south        12.0   316.666667

In [ ]:
dff1=pd.read_csv('/content/sales.csv')
dff1.head()

Date Region Product  Units_Sold  Unit_Price
0  2024-05-01   East  Laptop           5         700
1  2024-05-01   West   Phone          10         300
2  2024-05-02   East  Laptop           6         700
3  2024-05-02   West   Phone           8         300

In [ ]:
df.to_csv('/content/sales111.csv',index=False)

In [ ]:
df=pd.read_excel('/content/employee_data.xlsx')
df.head()

Emp_ID     Name Department
0     101    Alice         HR
1     102      Bob    Finance
2     103  Charlie         IT
3     104    David      Sales

In [ ]:
df.to_excel('/content/employee_data1223.xlsx',index=False)